require: rubocop-performance

Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  Max: 35

AllCops:
  Exclude:
    - db/migrate/*.rb
    - db/structure.sql
    - bin/*
    - script/*
    - config/routes.rb
    - 'spec/**/*'
    - vendor/**/*
    - node_modules/**/*

Style/Lambda:
  Enabled: false

Style/RedundantInterpolation:
  Enabled: false

Layout/FirstArgumentIndentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Security/JSONLoad:
  Enabled: false

