# require: rubocop-performance

Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  Max: 35

AllCops:
  Exclude:
    - db/migrate/*.rb
    - db/schema.rb
    - db/seeds.rb
    - db/structure.sql
    - bin/*
    - script/*
    - config/routes.rb


Style/Lambda:
  Enabled: false

Style/RedundantInterpolation:
  Enabled: false

Layout/FirstArgumentIndentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Security/JSONLoad:
  Enabled: false

