language: ruby 2.4.1
rvm:
- 2.4.1
notifications:
  email:
  - nyonmark@gmail.com
  - dariusgoore@gmail.com
  slack:
    secure: nGWlUFUuQjsn6zxJQqY6+ljlSHnz9We+OHi6UV4690Aw9RSDVmcNIGiCJB8DoySwYuppcTq/G2YEw5+vxHKRTWv0zHLNLQ8hfAlBxM5rPEFCrdvL+P9fQfZcuPGI2RUq4c0nCZ63a1Tgt3119kBw91qLGG4CWTMtcNO2mKMfNixdwwwbPKr/bqQHbgfi0zl66RKERBJdtljZneKD68AelFLm9YUtfOCNreY+sZ5LTaYEpG8REEqW1MJt3iI3lGs/YUscpwuyBa9fPoD5B6FUD9K9dS5rsjznYStB3dNqkoeVFZP0LQd1+Rk2GVwqmDfhAuCB5tUOH5zdET4U7sw8//ZzceAztABSEuKQVg4TUnSBBN4+vB1KDO8kFGItaY7xqFywIHvGXUu54e7XUgvMT5tfgblfNJTKbBx3loIydJmQTiRLGOChlKICi46kdzoOKCTiYxfCFsJvjTe7e5eE48Ardi6vnxFxOtPnbHIcrM1ImRfaYKJ1+5tZZEXtAnni4D9xcg3KMdsyTJsi4Obl51tH4BGy13gzG7HrsuRgLkAGYGjvDCf6W5tmktVz23R+JR3aGrBV1/AfPPYoJxXXsylt4kh5BY7gSGe2S8nw/hTI5VQ5GRrUhB8K9jmEE7nt4bBkQv1M/vXTs85HQvwyGK/UdS3nS86QnEmi0FIQmxA=
addons:
  postgresql: '9.4'
before_script:
- psql -c 'create database travis_ci_test;' -U postgres; cp config/database.ci.yml
  config/database.yml
- bundle exec rake db:create db:migrate db:schema:load
cache: bundler
services:
- elasticsearch
- redis-server
env:
  global:
  - secure: Bg74RCZIHenKp0bPcy2dzO7tyeOyC1oxvq+4BeysmdO00gFQI2ZTX/HQ6nql1IaCjjmB62Yy+bipEm7Ln3tPHUaPh9/7hOrGPi8SYVMn1us1/9rGm0imqhUnU+ErTtFOqS8ZDq7EMY0arkRcd6vhdQaVjyF7emLgx3r9xxXm+hc2MsfGnFDf5Xpp66H+eM9ra3Zgf4Gn10V4ZYDyGf+Z8n5DHxHBiiwzcsig+zeqg+M2mbBDNkR4rEPXmfcN5PQKzX9cPjT8hZ6Oq/NOlfA3lxbyiZ4hT71K84Dzbe9uO2aHNpiKr6kKa4aUPxDXb2hAf4YUWAJ0zS1CvZvTiRUW9Dgx1VgHC1gHoKXa2NLs5vYpaaItbGBRmo5k56K9fO2EuzO2rLLoDxvzXBK4Atq+22+L609dHKuJsVckIdDd5yDc0FcF8bUmvEn1a5DV2mjmMkIvDhnfmPyqJqK4OGrreWccg+c3roSR/pid4ls4atWTZppvrDcdTF9KigV/H34Tg/Evwogxld3kyrNHqe5aQIdluTq0pygEFAAVSWAvGMn7LgQKu/7MuGrHhqfeVdD7/G5sad0NSXlQNSx3PM7CjNPFQ3AAV6b1OsvVr1zhqXIa22fj18m6UPeCtqgNfEyowaa5X5nvE/aR2Uwt93whexWbKEeA5bhsvisS1LJlMoA=
  - secure: vro5qbwTcOuQPahSw1xn69W3b9wh2/vqDy6HyVgmYJI1czoeqGh7TxISxvb6s5fEInI3gxGCvKoVffxNdC+FEC8DNPETulvCSEB5/Lbr9G+DGNDkjq4Oj7LpKSunNw93cVJEk+hX9ISxg0W7jxj8QtMT7/V40wXcShfkr5ynq8H9tZzskg3HuwJ8IZS4JTHsCcy8PncuGK6u51/Id6Ns0NKDCNpsjkyjzR8+bpeZLC55mI7SuvbGlfXUJJaNSWk8SMQU5qQ1fqHMz/DDvvFkbpgCIawg8YEPnYhkUhkQjyb0zyPCNNfe1khU+ll6EEwrIZFdKLh3YfvTKBhSQ4kO2QdgrO2Aip9Ix2QPouO+grx+FYGIkNMKmyczFDamrb7QY+5KJNf7PQiWSi2ACdMSfX3ezbJGNwrbxaN3tskKeIncKKtB5wVq/GTHdoVEPNoWiSWLtkcNlM21YUl6DYq1SxnqNBjB4yX9zB03rW3w9wwo6tLL1w/7I+vKbuLGAgVDiCUYsAXar5vgF+DduQiVYWgtHWToI091cA0By3PABikMzpIs2JczkETjYq4GgtflerBgHoERNzDuwssIbpNNW09DLuPDTOkwXI6zTm2eMJHT8oF59jjYQKXOQWKxkicLlc/N2jPpE7uvfl003EG55PzJ4QtrOOLMg1p3uyTyQMU=
