language: ruby 2.6.5
rvm:
- 2.6.5
notifications:
  email:
  - nyonmark@gmail.com
  - dariusgoore@gmail.com
  - rlgreen91@gmail.com
  slack:
    secure: nGWlUFUuQjsn6zxJQqY6+ljlSHnz9We+OHi6UV4690Aw9RSDVmcNIGiCJB8DoySwYuppcTq/G2YEw5+vxHKRTWv0zHLNLQ8hfAlBxM5rPEFCrdvL+P9fQfZcuPGI2RUq4c0nCZ63a1Tgt3119kBw91qLGG4CWTMtcNO2mKMfNixdwwwbPKr/bqQHbgfi0zl66RKERBJdtljZneKD68AelFLm9YUtfOCNreY+sZ5LTaYEpG8REEqW1MJt3iI3lGs/YUscpwuyBa9fPoD5B6FUD9K9dS5rsjznYStB3dNqkoeVFZP0LQd1+Rk2GVwqmDfhAuCB5tUOH5zdET4U7sw8//ZzceAztABSEuKQVg4TUnSBBN4+vB1KDO8kFGItaY7xqFywIHvGXUu54e7XUgvMT5tfgblfNJTKbBx3loIydJmQTiRLGOChlKICi46kdzoOKCTiYxfCFsJvjTe7e5eE48Ardi6vnxFxOtPnbHIcrM1ImRfaYKJ1+5tZZEXtAnni4D9xcg3KMdsyTJsi4Obl51tH4BGy13gzG7HrsuRgLkAGYGjvDCf6W5tmktVz23R+JR3aGrBV1/AfPPYoJxXXsylt4kh5BY7gSGe2S8nw/hTI5VQ5GRrUhB8K9jmEE7nt4bBkQv1M/vXTs85HQvwyGK/UdS3nS86QnEmi0FIQmxA=
addons:
  postgresql: '9.4'
before_install:
- gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
- gem install bundler:1.16.2
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.ci.yml config/database.yml
- bundle exec rake db:create db:migrate db:structure:load
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./bin/cc-test-reporter
- chmod +x ./bin/cc-test-reporter
- "./bin/cc-test-reporter before-build"
cache: bundler
services:
- elasticsearch
- redis-server
after_script:
- "./bin/cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
env:
  global:
  - secure: AiluJroHNwdw6CGZ5IMK9ZK3n7C0JnR3PdyzZ0nxX7PznCP224wJHA/Uvpu3SG8HX95f6dfKcVo5/WZrMlgDWyB1fgm6Brpdvj+1ECU4nhQcajVU9Rezp9vGEcj723HsY2jTOSH2VGle6Zh0o3YgcNTy0vuzqrsBKzpMKHwIWSu7QJQBSvDBn3FmQDmCL29pWkk4FKyFS4eoM0B7VXZ7bAGKA/PJkOwBv9a+ZtSPT2xLLgDkFc7PFCuk28aHNJK5Iw3bL2YzFRbShT3yBoCGwBIHuca7EqIIQIvjHULBCG9McjX/1o/ODaEJZHN5dqXB3y8a0k4oypKLStS/nsxY58f3httJl9E0fq7vTNP6VYHBoHOlhEujUwYN/tAJVZ3hu7UwoQwXS7KeTXU+nY7RVtdzhPVmnuMTAL+FEkwAcbg2kYA/2FiHOqXmP8+bEDYKGvn+QqTXjYcK5L7gJp+i3G0grGWeM3oMGxe6wowQ2/wqUNTh8cgNkai3hKYxKXyjsDMQZQdwKd24xW8qT6XiLvY3U3v9Vs7Du1GA7YAsLLrhCSYhImWDd4H2sgTlghc7T2iSp4ufuPjAX80LRc0/foRi7QmpJ6/MQNAwOQKl7/0c9dAisrIV6asKM8WPdi0l4DrhOE5+vomaWBUBZQsc/Gvj+/T/ubZUfa3SSorpwbM=
  - secure: kaZDh2KmT0Zy+Sz7dETxUtNs2NAtxcKuT7RWXn/nwYe1vvgbLQ1KQzwImklP943TTpS9ciCkjLMXzlAFOHAK1fiHUu2CIvBJd6uSoDhiBLicFqoQLjnUjM4FcGZ5h9QQ6jMf7bou1QHoTNB7PnGzYpt4rN3tK1ctJ81KrfvkbkEr9FzygUyH2YDSa/JjjT6I0HakTxSyZXc2Hp3kn5r2GTmq+S8IZFf5mhlIXG55SOdLsv/omDwod2//oXsN0a/Y7fizZescgTRqpjrwe/B9K+zK98/ALnxlf2Oh7TTNjBCXtyki7JGTxwzFq2I/yYuAe1nCmNfTSUG5yL0N+p3yRnYo7liStpcHVVcdNz2LSMErGFJeANgf3t8A0AtMMterJVuIpLppgbXZfLoF98buArHpl6SWXMXs09Qq29Z8vpfgiUZ02RsvhUNMJa9UCN2B74thfxu1bhliIr4QsEuSdqkZ2GVyduVOk0xxZI/n2CEzAvmiqZiBQVSHVZnrJ6T4sfRpVMWriIPTN1CuHwJd0HY+3a9wOSBp6HrW4o2pwlZTjjj3VukWrAUsCI1PkPPyK3y/WXIHOxUYa34BqAs7rcig+EuMvg2bk5LWzSL3JeJ4H7PLHqOmH82oSSW14n9ikfvGQPcM/3edVVc1C21WMvC17+9Y7DW0T46t8P0Wjzo=
  - secure: DjXrqz8dtXcafG1UL5xZGnoRCQtOKkWVrhTjLPXN+qKQDLE5GWj1/X9JB5tcWAfPqFCwP6WWG5cxAOms7Dfc7drds68EgMQNpHrrBLxVXJ964DAu7eJEH6BqFvKCk7tvD7tRnnmYGEgTgYA3C/IjjUF6OBfXuuFofKpYvXmMXL9ph8/sVi10I6lZSvAqy+kw7Iy5VnI4oaS82gZZ/MovFfjMflJ1CY0bB6X6g3DlaQ3lyYmx1ksgNEnB+NgM+HNGQ0Aq2H/6/IeFPC7JQZbfCPVKi9d6NSArih9TP5KJy+7walmu2BOAyZpCmXAbk2vS2mSu0IcHH2eh/2SA3p+uJAeD7WE5VchE0aBJFQ4ZZsRicaa0yYbCCB+8pCOvbiY+C74kG/W8TRpvMCM3Igp2c9o6B3tJRk1wrODn1MI/JuJzhKsMftwVC+2uodNziFW8NYbzztjCD8NVcODp2qagkFziuDHUAp6ri0LLS6PVmRBb7br3ql53TmfQljgnoMxbmjXh0ZSN8qkiB2mn3/xgARDWYlV1eblsZvjxhxKTtpxCHnehxFWqLh1NnuW4Z5O9fM9wLl/fFqrdKhjT6LEc10otM+Vxm7N7FRIBIrPOqGqP10+q4yJQ3mkp8hZUHsexISGUKEH7K5/lae8TvCF2sBVYOb6k7+LHJb8guo2ib2Y=
