language: ruby 2.2.1

rvm:
  - 2.2.1

notifications:
 email:
   - nyonmark@gmail.com
   - dariusgoore@gmail.com
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec

# Select modern postgres
addons:
  postgresql: "9.4"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres; cp config/database.ci.yml config/database.yml
  - bundle exec rake db:create db:migrate db:schema:load

# Cache dependencies
cache: bundler