# frozen_string_literal: true

meta_title: "EBWiki - Ending Violence Against People of Color"
meta_description: "EBWiki is a web application working to harness the power of community to end bias in law enforcement that has led to disparate treatment of people of color with tragic results."
meta_keywords:
  - "police"
  - "killing"
  - "abuse"
meta_image: "EBWikiHeadLogo.png"
twitter_account: "@endbiaswiki"