name: Brakeman

on: [push, workflow_dispatch]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Run brakeman
        run: |
          PATH="$(ruby -r rubygems -e 'puts Gem.user_dir')/bin:$PATH"
          echo $PATH
          gem install --user-install brakeman
          brakeman -A --no-pager --no-exit-on-warn --no-exit-on-error
