name: Codeclimate Lite

on: [pull_request, push, workflow_dispatch]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Run codeclimate
        run: |
          make codeclimate
