---
name: Rspec

on: [pull_request, push, workflow_dispatch]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run rspec
        run: |
          make run rspec stop
