name: Rubocop

on: [push, workflow_dispatch]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Run rspec
        uses: ruby:2.6.5
        run: |
          gem install rubocop
          rubocop
