name: Rubocop

on: [push, workflow_dispatch]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Run rspec
        run: |
          PATH="$(ruby -r rubygems -e 'puts Gem.user_dir')/bin:$PATH"
          echo $PATH
          gem --user-install install rubocop
          rubocop
